#!/bin/bash

if [ "$1" = "-h" ]; then

  cat <<'END'
  Usage: commits-since-tag [TAGNAME] | -h
END
  exit

elif [ "$1" ]; then

  TAGNAME="$1"

else

  echo -e "\n\033[1mRecent tags\033[0m\n"
  git tag -n1 | sort -V | tail -20

  MOST_RECENT_TAG=$(git tag | sort -V | tail -1)

  read -p "Enter a tag, commit or branch [$MOST_RECENT_TAG] " TAGNAME

  TAGNAME="${TAGNAME:-$MOST_RECENT_TAG}"

fi

# Color ref: http://goo.gl/fesQsJ
echo -e "\n\033[1mCommits since \033[31m$TAGNAME\033[0m\n"
CMD="git log \"$TAGNAME\".. --no-merges --pretty=format:\"%h [%ad] [%cn]%C(auto)%d %s\" --graph --date=short"
echo -e "  \033[33m$CMD\033[0m\n"

eval $CMD
echo